"""Add pages_processed to Edition

Revision ID: 22c8d210d95c
Revises: 0d56c4ff1fd8
Create Date: 2026-01-24 05:12:05.320476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22c8d210d95c'
down_revision: Union[str, Sequence[str], None] = '0d56c4ff1fd8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('editions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pages_processed', sa.Integer(), nullable=False))

    with op.batch_alter_table('item_categories', schema=None) as batch_op:
        batch_op.create_unique_constraint('_item_category_uc', ['item_id', 'category_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('item_categories', schema=None) as batch_op:
        batch_op.drop_constraint('_item_category_uc', type_='unique')

    with op.batch_alter_table('editions', schema=None) as batch_op:
        batch_op.drop_column('pages_processed')

    # ### end Alembic commands ###
