"""add_user_model

Revision ID: 88da348970ce
Revises: 184385609c27
Create Date: 2026-01-23 09:24:21.557826

"""
from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = '88da348970ce'
down_revision: str | Sequence[str] | None = '184385609c27'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
