"""add_structured_data_field_to_items

Revision ID: a3ab24c21056
Revises: d165df953ed1
Create Date: 2026-01-23 12:46:58.211810

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'a3ab24c21056'
down_revision: str | Sequence[str] | None = 'd165df953ed1'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('structured_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'structured_data')
    # ### end Alembic commands ###
