"""Add structured classifieds fields to Item model

Revision ID: bd05b9fb1965
Revises: 51eba26c3c9a
Create Date: 2026-01-22 18:02:58.451288

"""
from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'bd05b9fb1965'
down_revision: str | Sequence[str] | None = '51eba26c3c9a'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('contact_info_json', sa.JSON(), nullable=True))
    op.add_column('items', sa.Column('price_info_json', sa.JSON(), nullable=True))
    op.add_column('items', sa.Column('date_info_json', sa.JSON(), nullable=True))
    op.add_column('items', sa.Column('location_info_json', sa.JSON(), nullable=True))
    op.add_column('items', sa.Column('classification_details_json', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'classification_details_json')
    op.drop_column('items', 'location_info_json')
    op.drop_column('items', 'date_info_json')
    op.drop_column('items', 'price_info_json')
    op.drop_column('items', 'contact_info_json')
    # ### end Alembic commands ###
